source 'https://cdn.cocoapods.org/'

def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__
  ]).strip
end

node_require('react-native/scripts/react_native_pods.rb')

platform :ios, '16.4'
prepare_react_native_project!

$RNFirebaseAsStaticFramework = true
use_frameworks! :linkage => :static

target 'Paw2me' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
