source 'https://cdn.cocoapods.org/'

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.4'
prepare_react_native_project!

target 'Paw2me' do
  config = use_native_modules!

  # Reanimated 4 → New Architecture (Fabric) activada
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled  => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # No fuerces Firebase “static framework”; evita el problema de GoogleUtilities
  $RNFirebaseAsStaticFramework = false

  # 👇 FIX quirúrgico: haz que GoogleUtilities genere module maps
  pod 'GoogleUtilities', :modular_headers => true

  # NADA de `use_frameworks!` aquí

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
