// Centralizamos el require del logo
// Nota: este archivo está en src/assets → la ruta correcta es ./logo/...
export const appLogo = require('./logo/app-logo.png');
// Si prefieres usar el set de Android, cambia la ruta por ./logo/android/144ppi/...
